networks:
  dev-fragforce-org: {}
  swag_bridge: {}

services:
  db:
    image: postgres:18.3
    container_name: dev-db
    restart: unless-stopped
    networks: [dev-fragforce-org]
    env_file: ./.env
    volumes:
      - ./postgres:/var/lib/postgresql
      - .:/dump
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis
    container_name: dev-redis
    restart: unless-stopped
    environment:
      TZ: "Etc/UTC"
    networks: [dev-fragforce-org]
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    image: ghcr.io/fragforce/fragforce-dev-web:dev
    container_name: dev-migrate
    command: python manage.py migrate
    networks: [dev-fragforce-org]
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  web:
    image: ghcr.io/fragforce/fragforce-dev-web:dev
    container_name: dev-web
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "10.22.195.4:8001:8000"
    environment:
      TZ: "Etc/UTC"
      DJANGO_LOG_LEVEL: "DEBUG"
    command: [ "gunicorn", "--log-level", "debug", "--bind=0.0.0.0:8000", "--forwarded-allow-ips", "*", "--proxy-allow-from", "*", "fforg.wsgi" ]
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - dev-fragforce-org
      - swag_bridge

  worker:
    image: ghcr.io/fragforce/fragforce-dev-worker:dev
    container_name: dev-worker
    restart: unless-stopped
    env_file: ./.env
    environment:
      DJANGO_LOG_LEVEL: "DEBUG"
    command: [ "celery", "-A", "fforg", "worker", "--autoscale=6,2", "-E" ]
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks: [dev-fragforce-org]

  beat:
    image: ghcr.io/fragforce/fragforce-dev-beat:dev
    container_name: dev-beat
    restart: unless-stopped
    env_file: ./.env
    environment:
      DJANGO_LOG_LEVEL: "DEBUG"
    command: [ "celery", "-A", "fforg", "worker", "--autoscale=1,1", "--beat", "-E" ]
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks: [dev-fragforce-org]
